### PR TITLE
[BUG] Fix status of undefined issue

### PR DESCRIPTION
**Pull request by yc-shawn**
image

Root casue: https://github.com/tech-gamers/side-project-incubator-web/commit/ef403c6f2969440b6ca75f3d5684a91a7b10686e

### CODE REVIEW

**Review by wangtjwork — APPROVED** [review]
Would it happen out of our design that ex is null? If not why add `ex?`

**Comment by robturtle** [comment]
```typescript
function foo({ response }: any) {
    if (response.status) {
        console.log(`captured ${response.status}`)
    } else {
        console.log("entered but not captured")
    }
}

foo({ response: { status: 400 } })
foo({ message: "other runtime error"})
```

image

@yc-shawn 标的根本不是 root cause。即使是原始代码，也完全没办法正确处理其他的 exception （狗头狗头（slogan: it's not easy to 甩锅 to me （狗头狗头

**Comment by robturtle** [comment]
> Would it happen out of our design that ex is null? If not why add `ex?`

@wangtjwork 

- no matter in what language I never see it was designed to allow "throwing nothing"
- why add `ex`? coz we wanna rethrow it.

**Comment by yc-shawn** [comment]
这两个加起来就是root case:
https://github.com/tech-gamers/side-project-incubator-web/pull/24/commits/4f274cb42afce5e3c696b6ad841dc9c1eedeb9c0
https://github.com/tech-gamers/side-project-incubator-web/commit/ef403c6f2969440b6ca75f3d5684a91a7b10686e

甩锅甩锅（狗头

**Pull request merged**
